//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define SCROLLINGTEST                   157
#define IDB_BITMAP3                     158
#define MAP01                           159
#define TestDog                         162
#define IDB_BITMAP4                     163
#define monsterTest                     163
#define m1                              164
#define R_P0                            166
#define R_P1                            167
#define R_P2                            168
#define R_P3                            169
#define R_P4                            170
#define R_P5                            171
#define R_P6                            172
#define L_P0                            173
#define L_P1                            174
#define L_P2                            175
#define L_P3                            176
#define L_P4                            177
#define L_P5                            178
#define L_P6                            179
#define R_J1                            180
#define R_J2                            181
#define L_J1                            182
#define L_J2                            183
#define HP16                            184
#define IDB_BITMAP5                     185
#define HP0                             185
#define IDB_BITMAP6                     186
#define HP1                             186
#define IDB_BITMAP7                     187
#define HP2                             187
#define IDB_BITMAP8                     188
#define HP3                             188
#define IDB_BITMAP9                     189
#define HP4                             189
#define HP5                             190
#define HP6                             191
#define HP7                             192
#define HP8                             193
#define HP9                             194
#define HP10                            195
#define HP11                            196
#define HP12                            197
#define HP13                            198
#define IDB_BITMAP20                    200
#define HP15                            200
#define HP14                            201
#define M1_0                            202
#define M1_1                            203
#define M1_2                            204
#define M1_3                            205
#define M1_4                            206
#define M1_5                            207
#define spear_L                         208
#define spear_r                         209
#define atk1_L                          210
#define atk2_L                          211
#define atk1_R                          212
#define atk2_R                          213
#define mb0                             214
#define mb1                             215
#define mb2                             216
#define mb3                             217
#define mb4                             218
#define mb5                             219
#define mb6                             220
#define mb7                             221
#define mb8                             222
#define mb9                             223
#define mb10                            224
#define mb11                            225
#define ground1                         226
#define ground2                         227
#define ground3                         228
#define ground4                         229
#define ground5                         230
#define ground6                         231
#define ground7                         232
#define gameover0                       233
#define gameover2                       234
#define gameover3                       235
#define gameover4                       236
#define gameover5                       237
#define gameover6                       238
#define gameover7                       239
#define gameover8                       240
#define menu0                           241
#define menu1                           242
#define menu2                           243
#define menu3                           244
#define dameage                         245
#define death1                          246
#define death2                          247
#define death3                          248
#define death4                          249
#define death5                          250
#define hp_0                            251
#define hp_1                            252
#define hp_button                       253
#define hp_top                          254
#define s0                              255
#define s1                              256
#define s2                              257
#define atk1_Rc                         258
#define atk2_Rc                         259
#define atk1_Lc                         260
#define IDB_BITMAP12                    261
#define atk2_Lc                         261
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
